// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AlertFilled: typeof import('@ant-design/icons-vue')['AlertFilled']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BulbFilled: typeof import('@ant-design/icons-vue')['BulbFilled']
    DesktopOutlined: typeof import('@ant-design/icons-vue')['DesktopOutlined']
    GithubFilled: typeof import('@ant-design/icons-vue')['GithubFilled']
    GithubOutlined: typeof import('@ant-design/icons-vue')['GithubOutlined']
    IeCircleFilled: typeof import('@ant-design/icons-vue')['IeCircleFilled']
    Info: typeof import('./src/components/Info.vue')['default']
    MenuOutlined: typeof import('@ant-design/icons-vue')['MenuOutlined']
    MessageFilled: typeof import('@ant-design/icons-vue')['MessageFilled']
    Pictorial: typeof import('./src/components/Pictorial.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlackCircleFilled: typeof import('@ant-design/icons-vue')['SlackCircleFilled']
  }
}
